# This is a basic workflow to help you get started with Actions

name: Call Cloud Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches:
    #- main
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  merge_job:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.8.0
      with:
        url: 'https://europe-west6-keen-phalanx-318406.cloudfunctions.net/calculate_cost'
        method: 'POST'
        data: '{"test data": "lorem ipsum cuhdiufheiufchvuivciuhefuvhiuefhviowhrvoihrwoivhiorhfiohrihfoiwh"}'
        
    - name: Logging to console
      run: echo "${{ github.event.pull_request.merged }}"
      
    - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
          PR: ${{ steps.findPr.outputs.pr }}
