name: Call Cloud Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches:
    #- main
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.8.0
      with:
        # url: 'https://europe-west6-keen-phalanx-318406.cloudfunctions.net/calculate_cost'
        url: 'https://europe-west6-coinpaper-blockchain.cloudfunctions.net/Reward'
        method: 'POST'
        data: '{"id": github.event.number}'
        
    - name: Logging to console
      run: echo "${{ github.event.pull_request.merged }}, PR Nr - ${{github.event.number}}"
